# Generated by Django 5.2.2 on 2025-06-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('wallet_address', models.CharField(max_length=255, unique=True)),
                ('user_type', models.CharField(choices=[('provider', 'Provider'), ('consumer', 'Consumer')], max_length=10)),
            ],
        ),
    ]
